### ISSUE TITLE
OVPN Oluşmuyor

### ISSUE THREAD

**Issue by tosunkaya** [boramalper/halkvpn#1]
İyi günler, bunu Azure Windows 10 VPS'te denedim. Masaüstünde .ovpn dosyası oluşturmuyor ve en sonunda "bilgisayar"ı açıyor. Ne yapabilirim? Olmazsa Linux makine açıp orada Outline serverı kuracağım. Teşekkürler. @boramalper

**Comment by boramalper** [comment]
Merhaba, aslına halkvpn oldukça kaba bir yöntem, insanlar hızlıca ve kolayca kurabilsin diye; yani kurulum sırasında ters gidebilecek pek çok şey var ve sizinkinde ters giden nedir tahmin edemiyorum.

Anladığım kadarıyla deneyimli birisisiniz, belki şu projeye < https://github.com/kylemanna/docker-openvpn > göz atmak istersiniz. Ben kendi sunucumda bunu kullanıyorum ve tıkır tıkır çalışıyor.
